import os
from PIL import Image

def generate_icons():
    # Source image generated by AI
    src_path = r"C:\Users\satha\.gemini\antigravity\brain\9146309f-726f-40f6-9f1a-0cd0db19434a\cathay_attendance_icon_1772630838652.png"
    if not os.path.exists(src_path):
        print(f"File not found: {src_path}")
        return

    # Base res directory
    res_dir = r"c:\Users\satha\.gemini\antigravity\scratch\msformsautofill\app\src\main\res"

    # Android icon sizes
    sizes = {
        "mipmap-mdpi": 48,
        "mipmap-hdpi": 72,
        "mipmap-xhdpi": 96,
        "mipmap-xxhdpi": 144,
        "mipmap-xxxhdpi": 192
    }

    try:
        with Image.open(src_path) as img:
            # Create a squircle crop to make it look like a standard app icon
            # (Simplifying here by just resizing, Android adaptive icons handle the masking)
            
            for folder, size in sizes.items():
                folder_path = os.path.join(res_dir, folder)
                os.makedirs(folder_path, exist_ok=True)
                
                # Standard icon (ic_launcher.png)
                resized = img.resize((size, size), Image.Resampling.LANCZOS)
                output_path = os.path.join(folder_path, "ic_launcher.png")
                resized.save(output_path, "PNG")
                
                # Round icon variant (ic_launcher_round.png) - just duplicating for simplicity
                # since the design is already centered
                output_round = os.path.join(folder_path, "ic_launcher_round.png")
                resized.save(output_round, "PNG")
                
                print(f"Generated {size}x{size} icons in {folder}")

            # Delete the XML launcher files that conflict with the PNGs
            xml_anydpi = os.path.join(res_dir, "mipmap-anydpi-v26")
            if os.path.exists(xml_anydpi):
                import shutil
                shutil.rmtree(xml_anydpi)
                print("Removed mipmap-anydpi-v26 XML files to force PNG usage")

        print("Successfully generated all launcher icons!")
        
    except Exception as e:
        print(f"Error processing image: {e}")

if __name__ == "__main__":
    generate_icons()
